palette = 0=#25263A
palette = 1=#94465D
palette = 2=#50A2A4
palette = 3=#D8CB68
palette = 4=#736CB4
palette = 5=#C27BA9
palette = 6=#8784C2
palette = 7=#E6E6E6
palette = 8=#393B5A
palette = 9=#C2666B
palette = 10=#58CBAA
palette = 11=#DDD472
palette = 12=#9A93D5
palette = 13=#CFAFDB
palette = 14=#A9A0D8
palette = 15=#F2F2F2
background = #25263A
foreground = #F3F3F3
cursor-color = #FFFFFF
cursor-text = #25263A
selection-background = #3D3F5E
selection-foreground = #FFFFFF
bold-is-bright = true
